#pragma once

#define NESTED_SHAPER_VERSION "1.1.1"

#define NESTED_SHAPER_MAJOR_VERSION 1
#define NESTED_SHAPER_MINOR_VERSION 1
#define NESTED_SHAPER_PATCH_VERSION 1
#define NESTED_SHAPER_TWEAK_VERSION "9bc556d"
