#pragma once

#define NESTED_SHAPER_VERSION "1.0.1"

#define NESTED_SHAPER_MAJOR_VERSION 1
#define NESTED_SHAPER_MINOR_VERSION 0
#define NESTED_SHAPER_PATCH_VERSION 1
#define NESTED_SHAPER_TWEAK_VERSION "7d2b814"
